#
# This is a project Makefile. It is assumed the directory this Makefile resides in is a
# project subdirectory.
#

PROJECT_NAME := BLE_demo
VERBOSE = 1 #user need to write own path to component 

include $(IDF_PATH)/make/project.mk
